const http=require('http'),fs=require('fs'),path=require('path');
const {Pool}=require('pg');
const html=fs.readFileSync(path.join(__dirname,'dist','index.html'),'utf8');
const codes={'RA-ALPHA-05':5,'RA-BETA-02':2,'RA-GAMMA-10':10};
const today=new Intl.DateTimeFormat('en-CA',{timeZone:'America/New_York',year:'numeric',month:'2-digit',day:'2-digit'}).format(new Date());
const pool=process.env.DATABASE_URL?new Pool({connectionString:process.env.DATABASE_URL,ssl:{rejectUnauthorized:false},max:3}):null;
const localUsage={};
let dbReady;
async function prepareDb(){if(!pool)return; if(!dbReady)dbReady=(async()=>{await pool.query('CREATE TABLE IF NOT EXISTS authorization_codes (code TEXT PRIMARY KEY, max_uses INTEGER NOT NULL, used_uses INTEGER NOT NULL DEFAULT 0)');for(const [code,max] of Object.entries(codes))await pool.query('INSERT INTO authorization_codes(code,max_uses) VALUES($1,$2) ON CONFLICT (code) DO NOTHING',[code,max]);})();return dbReady}
async function reserveUse(code){if(pool){await prepareDb();const r=await pool.query('UPDATE authorization_codes SET used_uses=used_uses+1 WHERE code=$1 AND used_uses<max_uses RETURNING max_uses,used_uses',[code]);if(!r.rowCount){const exists=await pool.query('SELECT 1 FROM authorization_codes WHERE code=$1',[code]);return {error:exists.rowCount?'exhausted':'invalid'};}return {remaining:r.rows[0].max_uses-r.rows[0].used_uses};}const max=codes[code]||0;if(!max)return {error:'invalid'};const used=localUsage[code]||0;if(used>=max)return {error:'exhausted'};localUsage[code]=used+1;return {remaining:max-localUsage[code]};}
async function releaseUse(code){if(pool)await pool.query('UPDATE authorization_codes SET used_uses=used_uses-1 WHERE code=$1 AND used_uses>0',[code]);else if(localUsage[code])localUsage[code]--;}
const send=(res,data,status=200)=>{res.writeHead(status,{'content-type':'application/json; charset=utf-8','access-control-allow-origin':'*'});res.end(JSON.stringify(data));};
async function analyze(req,res){let raw='';for await(const chunk of req)raw+=chunk;let b;try{b=JSON.parse(raw)}catch{return send(res,{error:'请求格式不正确。'},400)}const code=String(b.code||'').toUpperCase();let reservation;try{reservation=await reserveUse(code)}catch(e){return send(res,{error:'授权码服务暂时不可用，请联系安妮。'},503)}if(reservation.error==='invalid')return send(res,{error:'授权码无效，请联系安妮。'},401);if(reservation.error==='exhausted')return send(res,{error:'该授权码已无剩余次数。'},429);const text=String(b.resumeText||'').trim();if(text.length<40){await releaseUse(code);return send(res,{error:'未能读取到足够的简历文字，请上传 PDF 或 Word 文件。'},400)}const key=process.env.DEEPSEEK_API_KEY,model=process.env.DEEPSEEK_MODEL||'deepseek-flash',base=(process.env.DEEPSEEK_BASE_URL||'https://api.deepseek.com').replace(/\/$/,'');if(!key){await releaseUse(code);return send(res,{error:'分析服务尚未配置，请联系安妮。'},503)}const prompt=`你是北美求职简历顾问。当前日期是 ${today}，时区是 America/New_York。日期判断必须以此为准：2026 年 5 月已经过去，不得标记为未来时间。请根据下面的简历原文和求职背景，给出真实、可执行的修改结果。严格保留事实，不编造经历、数字、雇主或学历。输出中文，包含：1) 一句话职业定位；2) 最需要修改的5项；3) 可直接替换的Summary；4) 3条示范性经历bullet（只基于原文事实）；5) 版式和ATS可读性建议；6) 需要向候选人确认的信息。目标方向：${b.role||'未填写'}；职业阶段：${b.level||'未填写'}；优先项：${b.priorities||'未填写'}；备注：${b.notes||'无'}。简历原文：\n${text.slice(0,30000)}`;try{const up=await fetch(base+'/chat/completions',{method:'POST',headers:{'content-type':'application/json',authorization:'Bearer '+key},body:JSON.stringify({model,messages:[{role:'user',content:prompt}],temperature:0.2,thinking:{type:'disabled'},max_tokens:3000})});const data=await up.json();if(!up.ok){await releaseUse(code);return send(res,{error:data?.error?.message||'AI 分析服务暂时不可用。'},502)}send(res,{remaining:reservation.remaining,feedback:data.choices?.[0]?.message?.content||'模型未返回文本。'});}catch(e){await releaseUse(code);send(res,{error:'AI 分析请求失败，请联系安妮。'},502)}}
http.createServer((req,res)=>{const u=new URL(req.url,'http://localhost');if(u.pathname==='/api/analyze'&&req.method==='POST')return analyze(req,res);if(u.pathname==='/'||u.pathname==='/index.html'){res.writeHead(200,{'content-type':'text/html; charset=utf-8'});return res.end(html)}const asset=path.basename(u.pathname),file=path.join(__dirname,'dist',asset),types={'.png':'image/png','.jpg':'image/jpeg','.jpeg':'image/jpeg','.ico':'image/x-icon'};if(file.startsWith(path.join(__dirname,'dist'))&&fs.existsSync(file)&&types[path.extname(file)]){res.writeHead(200,{'content-type':types[path.extname(file)]});return fs.createReadStream(file).pipe(res)}res.writeHead(404);res.end('Not found')}).listen(process.env.PORT||10000,'0.0.0.0');
